version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: file-parser-api
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    environment:
      - APP_NAME=File Parsing API
      - DEBUG=true
      - UPLOAD_DIR=/tmp/uploads
      - RATE_LIMIT=10/minute
      - OCR_LANG=eng
      - LOG_LEVEL=INFO
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./logs:/app/logs
    restart: unless-stopped

